### ISSUE TITLE
Can't install the VSIX anymore

### ISSUE THREAD

**Issue by VioletGiraffe** [VioletGiraffe/cppcheck-vs-addin#109]
When I run the VSIX on my main working computer, I get an error: 

` Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'cppcheck add-in' requires a version of the .NET Framework that is not installed.`

This is a VSIX built with VS 2013. At the same time, if I open the solution in VS 2013 and launch debug, debugging works fine.

Thoughts?

**Comment by VioletGiraffe** [comment]
Same thing with VSIX built in VS 2012.

**Comment by Dmitry-Me** [comment]
Where do I get the VSIX?

**Comment by VioletGiraffe** [comment]
bin/Debug/CppcheckPlugin.vsix

**Comment by Dmitry-Me** [comment]
I cannot reproduce the problem. Do you have an idea of when it appeared for the first time? Maybe there's a specific commit such that it doesn't occur before that commit?

**Comment by VioletGiraffe** [comment]
It happened before the last time I committed and today, and the problem is not with the source code - I've reverted back to where it certainly worked, and still got the same error. It's something in my environment. I just thought you might know what could cause it.

**Comment by Dmitry-Me** [comment]
Not a slightest idea.

**Comment by halex2005** [comment]
Today I decide to install VSIX v1.2.1 and I have similar problem.
I tryed to install v1.2.1, v1.2.0, v1.1.0 but every time error was same - `The extension 'cppcheck add-in' requires a version of the .NET Framework that is not installed`.

I think it is not source code bug, but Visual Studio. I installed Visual Studio CTP5 two weeks ago and found some problems with my OS since then like hangs on creating System Restore Point.

**Comment by VioletGiraffe** [comment]
It's definitely not a source code bug or VSIX file bug. It's a bug in our local environment.

**Comment by mkurdej** [comment]
Actually the problem comes from the fact that VS 2015 CTP / RC comes with .NET 4.6 RC and so .NET 4.5 is no more seen by VSIX.
The solution is to:
1. handle both 4.5 and 4.6 [as it will be soon necessary anyway if targeting VS 2015/Win10], or
2. uninstall .NET 4.6 if possible (or uninstall Windows Update KB3033094/KB3033095).
